In [5]:
import pandas as pd
df=pd.read_csv("jpm_weekly_return_volatility.csv")
df["+/-"]=df["Label"].apply(lambda x: "+" if x == "green" else "-")
df_tr=df[(df["Year"]==2019)|(df["Year"]==2020)|(df["Year"]==2021)]
df_t=df[(df["Year"]==2022)|(df["Year"]==2023)]
df.head(6)

   Year  Week_Number  mean_return  volatility  Label +/-
0  2019            0     0.755333    2.636439  green   +
1  2019            1    -0.155400    0.210286    red   -
2  2019            2     0.920600    0.451274  green   +
3  2019            3    -0.285000    0.936882    red   -
4  2019            4     0.095600    0.548815  green   +
5  2019            5    -0.488000    0.678885    red   -

In [15]:
import pandas as pd
import pandas as pd
df_t.reset_index(drop=True, inplace=True)
print(len(df_t))
df_t["Predicted_2"]=None
df_t["Predicted_2"][0]="+"
df_t["Predicted_2"][1]="-"
for i in range(2, len(df_t)):

    x=df_t['Predicted_2'].iloc[i-2]
    y=df_t['Predicted_2'].iloc[i-1]
    a=((df_tr["+/-"] == x) & (df_tr["+/-"].shift(-1) == y) & (df_tr["+/-"].shift(-2) == '+')).sum()
    b=((df_tr["+/-"] == x) & (df_tr["+/-"].shift(-1) == y) & (df_tr["+/-"].shift(-2) == '-')).sum()
    if a > b:
        pred = '+'
    else:
        pred = '-'

    df_t.at[i,'Predicted_2'] = pred

print(df_t.head(5))

104

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9268\2075645103.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t["Predicted_2"]=None
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9268\2075645103.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t["Predicted_2"][0]="+"
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9268\2075645103.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t["Predicted_2"][1]="-"

   Year  Week_Number  mean_return  volatility  Label +/- Predicted_2
0  2022            1       1.2264    2.048192  green   +           +
1  2022            2      -1.1012    2.831380    red   -           -
2  2022            3      -2.0850    1.456614    red   -           -
3  2022            4       0.2160    1.201691  green   +           -
4  2022            5       0.8084    1.547716  green   +           -

In [16]:
import pandas as pd
import pandas as pd
df_t.reset_index(drop=True, inplace=True)
print(len(df_t))
df_t["Predicted_3"]=None
df_t["Predicted_3"][0]="+"
df_t["Predicted_3"][1]="-"
df_t["Predicted_3"][2]="+"
for i in range(3, len(df_t)):

    x=df_t['Predicted_3'].iloc[i-3]
    y=df_t['Predicted_3'].iloc[i-2]
    z=df_t['Predicted_3'].iloc[i-1]
    a=((df_tr["+/-"] == x) & (df_tr["+/-"].shift(-1) == y) & (df_tr["+/-"].shift(-2) == z) & (df_tr["+/-"].shift(-3)  == "+")).sum()
    b=((df_tr["+/-"] == x) & (df_tr["+/-"].shift(-1) == y) & (df_tr["+/-"].shift(-2) == z) & (df_tr["+/-"].shift(-3)  == "-")).sum()
    if a > b:
        pred = '+'
    else:
        pred = '-'

    df_t.at[i,'Predicted_3'] = pred

print(df_t.head(5))

104

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9268\1901966978.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t["Predicted_3"]=None
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9268\1901966978.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t["Predicted_3"][0]="+"
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9268\1901966978.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t["Predicted_3"][1]="-"
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9268\1901966978.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t["Predicted_3"][2]="+"

   Year  Week_Number  mean_return  volatility  Label +/- Predicted_2  \
0  2022            1       1.2264    2.048192  green   +           +
1  2022            2      -1.1012    2.831380    red   -           -
2  2022            3      -2.0850    1.456614    red   -           -
3  2022            4       0.2160    1.201691  green   +           -
4  2022            5       0.8084    1.547716  green   +           -

  Predicted_3
0           +
1           -
2           +
3           -
4           -

In [17]:
import pandas as pd
import pandas as pd
df_t.reset_index(drop=True, inplace=True)
print(len(df_t))
df_t["Predicted_4"]=None
df_t["Predicted_4"][0]="+"
df_t["Predicted_4"][1]="-"
df_t["Predicted_4"][2]="+"
df_t["Predicted_4"][3]="-"
for i in range(3, len(df_t)):

    x=df_t['Predicted_4'].iloc[i-4]
    y=df_t['Predicted_4'].iloc[i-3]
    z=df_t['Predicted_4'].iloc[i-2]
    e=df_t['Predicted_4'].iloc[i-1]
    a=((df_tr["+/-"] == x) & (df_tr["+/-"].shift(-1) == y) & (df_tr["+/-"].shift(-2) == z) & (df_tr["+/-"].shift(-3) == e) & (df_tr["+/-"].shift(-4) == "+")).sum()
    b=((df_tr["+/-"] == x) & (df_tr["+/-"].shift(-1) == y) & (df_tr["+/-"].shift(-2) == z) & (df_tr["+/-"].shift(-3) == e) & (df_tr["+/-"].shift(-4) == "+")).sum()
    if a > b:
        pred = '+'
    else:
        pred = '-'

    df_t.at[i,'Predicted_4'] = pred

print(df_t.head(5))

104

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9268\2037469819.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t["Predicted_4"]=None
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9268\2037469819.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t["Predicted_4"][0]="+"
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9268\2037469819.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t["Predicted_4"][1]="-"
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9268\2037469819.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t["Predicted_4"][2]="+"
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9268\2037469819.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t["Predicted_4"][3]="-"

   Year  Week_Number  mean_return  volatility  Label +/- Predicted_2  \
0  2022            1       1.2264    2.048192  green   +           +
1  2022            2      -1.1012    2.831380    red   -           -
2  2022            3      -2.0850    1.456614    red   -           -
3  2022            4       0.2160    1.201691  green   +           -
4  2022            5       0.8084    1.547716  green   +           -

  Predicted_3 Predicted_4
0           +           +
1           -           -
2           +           +
3           -           -
4           -           -

In [18]:
df_t['ensemble'] = df_t[["Predicted_2","Predicted_3","Predicted_4"]].mode(axis=1).iloc[:, 0]
df_t.head(5)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9268\3749456701.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t['ensemble'] = df_t[["Predicted_2","Predicted_3","Predicted_4"]].mode(axis=1).iloc[:, 0]

,Year,Week_Number,mean_return,volatility,Label,+/-,Predicted_2,Predicted_3,Predicted_4,ensemble
0,2022,1,1.2264,2.048192,green,+,+,+,+,+
1,2022,2,-1.1012,2.831380,red,-,-,-,-,-
2,2022,3,-2.0850,1.456614,red,-,-,+,+,+
3,2022,4,0.2160,1.201691,green,+,-,-,-,-
4,2022,5,0.8084,1.547716,green,+,-,-,-,-

In [19]:
a2=(df_t["Predicted_2"]==df_t["+/-"]).sum()/len(df_t)*100
a3=(df_t["Predicted_3"]==df_t["+/-"]).sum()/len(df_t)*100
a4=(df_t["Predicted_4"]==df_t["+/-"]).sum()/len(df_t)*100
print(a2,a3,a4)

50.0 49.03846153846153 49.03846153846153

In [20]:
aensemble=(df_t["ensemble"]==df_t["+/-"]).sum()/len(df_t)*100
print(aensemble)

49.03846153846153

In [21]:
minus_2 = ((df_t['Predicted_2'] == '-') & (df_t['+/-'] == '-')).sum()/len(df_t)*100
plus_2 = ((df_t['Predicted_2'] == '+') & (df_t['+/-'] == '+')).sum()/len(df_t)*100
minus_3 = ((df_t['Predicted_3'] == '-') & (df_t['+/-'] == '-')).sum()/len(df_t)*100
plus_3 = ((df_t['Predicted_3'] == '+') & (df_t['+/-'] == '+')).sum()/len(df_t)*100
minus_4 = ((df_t['Predicted_4'] == '-') & (df_t['+/-'] == '-')).sum()/len(df_t)*100
plus_4 = ((df_t['Predicted_4'] == '+') & (df_t['+/-'] == '+')).sum()/len(df_t)*100
minus_ensemble = ((df_t['ensemble'] == '-') & (df_t['+/-'] == '-')).sum()/len(df_t)*100
plus_ensemble = (((df_t['ensemble'] == '+') & (df_t['+/-'] == '+')).sum()/len(df_t))*100
print(minus_2,"\n",minus_3,"\n",minus_4,"\n",minus_ensemble,"\n",plus_2,"\n",plus_3,"\n",plus_4,"\n",plus_ensemble)

49.03846153846153
 48.07692307692308
 48.07692307692308
 48.07692307692308
 0.9615384615384616
 0.9615384615384616
 0.9615384615384616
 0.9615384615384616

In [22]:
TP2=((df_t['Predicted_2'] == '+') & (df_t['+/-'] == '+')).sum()
FP2=((df_t['Predicted_2'] == '+') & (df_t['+/-'] == '-')).sum()
TN2=((df_t['Predicted_2'] == '-') & (df_t['+/-'] == '-')).sum()
FN2=((df_t['Predicted_2'] == '-') & (df_t['+/-'] == '+')).sum()
TPR2=TP2/(TP2+FN2)
TNR2=TN2/(TN2+FP2)
print(TP2,FP2,TN2,FN2,TPR2,TNR2)

1 0 51 52 0.018867924528301886 1.0

In [23]:
TP3=((df_t['Predicted_3'] == '+') & (df_t['+/-'] == '+')).sum()
FP3=((df_t['Predicted_3'] == '+') & (df_t['+/-'] == '-')).sum()
TN3=((df_t['Predicted_3'] == '-') & (df_t['+/-'] == '-')).sum()
FN3=((df_t['Predicted_3'] == '-') & (df_t['+/-'] == '+')).sum()
TPR3=TP3/(TP3+FN3)
TNR3=TN3/(TN3+FP3)
print(TP3,FP3,TN3,FN3,TPR3,TNR3)

1 1 50 52 0.018867924528301886 0.9803921568627451

In [24]:
TP4=((df_t['Predicted_4'] == '+') & (df_t['+/-'] == '+')).sum()
FP4=((df_t['Predicted_4'] == '+') & (df_t['+/-'] == '-')).sum()
TN4=((df_t['Predicted_4'] == '-') & (df_t['+/-'] == '-')).sum()
FN4=((df_t['Predicted_4'] == '-') & (df_t['+/-'] == '+')).sum()
TPR4=TP4/(TP4+FN4)
TNR4=TN4/(TN4+FP4)
print(TP4,FP4,TN4,FN4,TPR4,TNR4)

1 1 50 52 0.018867924528301886 0.9803921568627451

In [25]:
TPe=((df_t['ensemble'] == '+') & (df_t['+/-'] == '+')).sum()
FPe=((df_t['ensemble'] == '+') & (df_t['+/-'] == '-')).sum()
TNe=((df_t['ensemble'] == '-') & (df_t['+/-'] == '-')).sum()
FNe=((df_t['ensemble'] == '-') & (df_t['+/-'] == '+')).sum()
TPRe=TPe/(TPe+FNe)
TNRe=TNe/(TNe+FPe)
print(TPe,FPe,TNe,FNe,TPRe,TNRe)

1 1 50 52 0.018867924528301886 0.9803921568627451

In [26]:
df_t["I1"]=None
df_t["I1"]= df_tr["+/-"].shift(+1)
df_t["I1"][0]="+"
df_t.head(5)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9268\659725704.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t["I1"]=None
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9268\659725704.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t["I1"]= df_tr["+/-"].shift(+1)
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9268\659725704.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t["I1"][0]="+"

,Year,Week_Number,mean_return,volatility,Label,+/-,Predicted_2,Predicted_3,Predicted_4,ensemble,I1
0,2022,1,1.2264,2.048192,green,+,+,+,+,+,+
1,2022,2,-1.1012,2.831380,red,-,-,-,-,-,+
2,2022,3,-2.0850,1.456614,red,-,-,+,+,+,-
3,2022,4,0.2160,1.201691,green,+,-,-,-,-,+
4,2022,5,0.8084,1.547716,green,+,-,-,-,-,-

In [27]:
df_t.to_csv("megafileres.csv")

In [38]:
df1=pd.read_csv("jpm_weekly_return_detailed.csv")
df1=pd.merge(df1, df_t, on=['Year', 'Week_Number',"mean_return","volatility","Label"], how='left')
df1.head()

,Open,High,Low,Close,Adj Close,Volume,Return,Date,Week_Number,Year,...,Weekday,mean_return,volatility,Label,+/-,Predicted_2,Predicted_3,Predicted_4,ensemble,I1
0,95.949997,99.779999,95.940002,99.309998,84.811668,15670900,0.000,1/2/2019,0,2019,...,Wednesday,0.755333,2.636439,green,NaN,NaN,NaN,NaN,NaN,NaN
1,98.639999,98.889999,96.690002,97.110001,83.606339,16286400,-1.421,1/3/2019,0,2019,...,Thursday,0.755333,2.636439,green,NaN,NaN,NaN,NaN,NaN,NaN
2,99.110001,100.930000,98.279999,100.690002,86.688560,16935200,3.687,1/4/2019,0,2019,...,Friday,0.755333,2.636439,green,NaN,NaN,NaN,NaN,NaN,NaN
3,100.430000,101.470001,99.709999,100.760002,86.748802,15430700,0.069,1/7/2019,1,2019,...,Monday,-0.155400,0.210286,red,NaN,NaN,NaN,NaN,NaN,NaN
4,101.629997,101.820000,99.550003,100.570000,86.585236,13578800,-0.189,1/8/2019,1,2019,...,Tuesday,-0.155400,0.210286,red,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df1["daily_returns"] = df1["Adj Close"].pct_change()
# Calculate weekly returns based on 'Year' and 'Week_Number'
weekly_returns = df1.groupby(['Year', 'Week_Number'])['daily_returns'].apply(lambda x: (1 + x).prod() - 1)
# Merge the weekly returns with the original DataFrame
df1 = pd.merge(df1, weekly_returns.rename('weekly_returns'), on=['Year', 'Week_Number'], how='left')
df1['R'] = df1['weekly_returns']
df1["Predicted_2"]=df1["Predicted_2"].apply(lambda x: "green" if x=="+" else "red")
df1["Predicted_3"]=df1["Predicted_3"].apply(lambda x: "green" if x=="+" else "red")
df1["Predicted_4"]=df1["Predicted_4"].apply(lambda x: "green" if x=="+" else "red")
df1["ensemble"]=df1["ensemble"].apply(lambda x: "green" if x=="+" else "red")
df1["I1"]=df1["I1"].apply(lambda x: "green" if x=="+" else "red")
df1.head()

,Open,High,Low,Close,Adj Close,Volume,Return,Date,Week_Number,Year,...,Label,+/-,Predicted_2,Predicted_3,Predicted_4,ensemble,I1,daily_returns,weekly_returns,R
0,95.949997,99.779999,95.940002,99.309998,84.811668,15670900,0.000,1/2/2019,0,2019,...,green,NaN,red,red,red,red,red,NaN,0.022130,0.022130
1,98.639999,98.889999,96.690002,97.110001,83.606339,16286400,-1.421,1/3/2019,0,2019,...,green,NaN,red,red,red,red,red,-0.014212,0.022130,0.022130
2,99.110001,100.930000,98.279999,100.690002,86.688560,16935200,3.687,1/4/2019,0,2019,...,green,NaN,red,red,red,red,red,0.036866,0.022130,0.022130
3,100.430000,101.470001,99.709999,100.760002,86.748802,15430700,0.069,1/7/2019,1,2019,...,red,NaN,red,red,red,red,red,0.000695,-0.007747,-0.007747
4,101.629997,101.820000,99.550003,100.570000,86.585236,13578800,-0.189,1/8/2019,1,2019,...,red,NaN,red,red,red,red,red,-0.001886,-0.007747,-0.007747

In [40]:
df1.columns

Index(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume', 'Return', 'Date',
       'Week_Number', 'Year', 'Day', 'Weekday', 'mean_return', 'volatility',
       'Label', '+/-', 'Predicted_2', 'Predicted_3', 'Predicted_4', 'ensemble',
       'I1', 'daily_returns', 'weekly_returns', 'R'],
      dtype='object')

In [53]:
import pandas as pd

cash = 100  #given amount in the problem
first_green_week = None 

# Find the first green week in the given year
for i in range(1, 53):
    if ((df1["Year"]==2022) & (df1["Week_Number"] == i) & (df1["Predicted_2"] == "green")).any():
        first_green_week = i
        cash = 0
        s=100/(df1.loc[df1["Week_Number"] == i, "Open"].iloc[0])
        break
cash=s*df1.loc[(df1['Year'] == 2023) & (df1['Week_Number'] == 52),"Adj Close"].iloc[-1]
print(cash)

168.33370546151437

In [59]:
import pandas as pd

def calculate_cash_for_year(df_year, cash):
    first_green_week = None 

    # Find the first green week in the given year
    for i in range(1, 53):
        if ((df_year["Week_Number"] == i) & (df_year["Predicted_2"] == "green")).any():
            first_green_week = i
            s = cash / df_year.loc[df_year["Week_Number"] == i, "Open"].iloc[0]
            cash = 0
            break

    # starting from first_green_week
    if first_green_week is not None:
        for i in range(first_green_week, 53): 
            if ((df_year["Week_Number"] == i) & (df_year["Predicted_2"] == "green")).any():
                if ((df_year["Week_Number"] == i+1) & (df_year["Predicted_2"] == "red")).any():
                    cash = s * df_year.loc[(df_year["Predicted_2"] == "green"), "Adj Close"].iloc[-1]
                else:
                    cash = s * df_year.loc[df_year["Week_Number"] == i, "Adj Close"].iloc[0] * (1 + df_year.loc[(df["Week_Number"] == i) & (df_year["Predicted_2"] == "green"), "R"].iloc[0] / 100)
            else:
                if ((df_year["Week_Number"] == i) & (df_year["Predicted_2"] == "red")).any():
                    if ((df_year["Week_Number"] == i+1) & (df_year["Predicted_2"] == "green")).any():
                        s = cash / df_year.loc[df_year["Week_Number"] == i+1, "Open"].iloc[0]
                        cash = 0
                    else:
                        continue

    return cash
years = range(2023, 2024)
y = []
initial_cash = calculate_cash_for_year(df1[df1["Year"] == 2022], 100)# Calculate initial cash for 2020
print("Cash at the end of 2022 is:", initial_cash)
y.append(initial_cash)

for year in years:
    df_year = df1[df1["Year"] == year]
    cash = calculate_cash_for_year(df_year, y[-1])  # Use the previous year's cash
    print("Cash at the end of", year, "is:", cash)
    y.append(cash)

print("Total cash across all years:", sum(y))

Cash at the end of 2022 is: 98.41605830695838
Cash at the end of 2023 is: 98.41605830695838
Total cash across all years: 196.83211661391675

In [60]:
import pandas as pd

cash = 100  #given amount in the problem
first_green_week = None 

# Find the first green week in the given year
for i in range(1, 53):
    if ((df1["Year"]==2022) & (df1["Week_Number"] == i) & (df1["ensemble"] == "green")).any():
        first_green_week = i
        cash = 0
        s=100/(df1.loc[df1["Week_Number"] == i, "Open"].iloc[0])
        break
cash=s*df1.loc[(df1['Year'] == 2023) & (df1['Week_Number'] == 52),"Adj Close"].iloc[-1]
print(cash)

168.33370546151437

In [61]:
import pandas as pd

def calculate_cash_for_year(df_year, cash):
    first_green_week = None 

    # Find the first green week in the given year
    for i in range(1, 53):
        if ((df_year["Week_Number"] == i) & (df_year["ensemble"] == "green")).any():
            first_green_week = i
            s = cash / df_year.loc[df_year["Week_Number"] == i, "Open"].iloc[0]
            cash = 0
            break

    # starting from first_green_week
    if first_green_week is not None:
        for i in range(first_green_week, 53): 
            if ((df_year["Week_Number"] == i) & (df_year["ensemble"] == "green")).any():
                if ((df_year["Week_Number"] == i+1) & (df_year["ensemble"] == "red")).any():
                    cash = s * df_year.loc[(df_year["ensemble"] == "green"), "Adj Close"].iloc[-1]
                else:
                    cash = s * df_year.loc[df_year["Week_Number"] == i, "Adj Close"].iloc[0] * (1 + df_year.loc[(df["Week_Number"] == i) & (df_year["ensemble"] == "green"), "R"].iloc[0] / 100)
            else:
                if ((df_year["Week_Number"] == i) & (df_year["ensemble"] == "red")).any():
                    if ((df_year["Week_Number"] == i+1) & (df_year["ensemble"] == "green")).any():
                        s = cash / df_year.loc[df_year["Week_Number"] == i+1, "Open"].iloc[0]
                        cash = 0
                    else:
                        continue

    return cash
years = range(2023, 2024)
y = []
initial_cash = calculate_cash_for_year(df1[df1["Year"] == 2022], 100)# Calculate initial cash for 2020
print("Cash at the end of 2022 is:", initial_cash)
y.append(initial_cash)

for year in years:
    df_year = df1[df1["Year"] == year]
    cash = calculate_cash_for_year(df_year, y[-1])  # Use the previous year's cash
    print("Cash at the end of", year, "is:", cash)
    y.append(cash)

print("Total cash across all years:", sum(y))

Cash at the end of 2022 is: 74.87043807388679
Cash at the end of 2023 is: 74.87043807388679
Total cash across all years: 149.74087614777358

In [62]:
import pandas as pd

cash = 100  #given amount in the problem
first_green_week = None 

# Find the first green week in the given year
for i in range(1, 53):
    if ((df1["Year"]==2022) & (df1["Week_Number"] == i) & (df1["I1"] == "green")).any():
        first_green_week = i
        cash = 0
        s=100/(df1.loc[df1["Week_Number"] == i, "Open"].iloc[0])
        break
cash=s*df1.loc[(df1['Year'] == 2023) & (df1['Week_Number'] == 52),"Adj Close"].iloc[-1]
print(cash)

168.33370546151437

In [64]:
import pandas as pd

def calculate_cash_for_year(df_year, cash):
    first_green_week = None 

    # Find the first green week in the given year
    for i in range(1, 53):
        if ((df_year["Week_Number"] == i) & (df_year["I1"] == "green")).any():
            first_green_week = i
            s = cash / df_year.loc[df_year["Week_Number"] == i, "Open"].iloc[0]
            cash = 0
            break

    # starting from first_green_week
    if first_green_week is not None:
        for i in range(first_green_week, 53): 
            if ((df_year["Week_Number"] == i) & (df_year["I1"] == "green")).any():
                if ((df_year["Week_Number"] == i+1) & (df_year["I1"] == "red")).any():
                    cash = s * df_year.loc[(df_year["I1"] == "green"), "Adj Close"].iloc[-1]
                else:
                    cash = s * df_year.loc[df_year["Week_Number"] == i, "Adj Close"].iloc[0] * (1 + df_year.loc[(df_year["Week_Number"] == i) & (df_year["I1"] == "green"), "R"].iloc[0] / 100)
            else:
                if ((df_year["Week_Number"] == i) & (df_year["I1"] == "red")).any():
                    if ((df_year["Week_Number"] == i+1) & (df_year["I1"] == "green")).any():
                        s = cash / df_year.loc[df_year["Week_Number"] == i+1, "Open"].iloc[0]
                        cash = 0
                    else:
                        continue

    return cash
years = range(2023, 2024)
y = []
initial_cash = calculate_cash_for_year(df1[df1["Year"] == 2022], 100)# Calculate initial cash for 2020
print("Cash at the end of 2022 is:", initial_cash)
y.append(initial_cash)

for year in years:
    df_year = df1[df1["Year"] == year]
    cash = calculate_cash_for_year(df_year, y[-1])  # Use the previous year's cash
    print("Cash at the end of", year, "is:", cash)
    y.append(cash)

print("Total cash across all years:", sum(y))

Cash at the end of 2022 is: 82.50536514101493
Cash at the end of 2023 is: 338.3216457354633
Total cash across all years: 420.8270108764782